backend:
  name: github
  repo: tomasz-enzo/bootcamp2026
  branch: main

media_folder: "images"

collections:
  - name: "config"
    label: "Ustawienia ogólne"
    files:
      - name: "general"
        label: "Data, miejsce, teksty"
        file: "content/config.json"
        fields:
          - {label: "Tytuł", name: "tytul", widget: "string"}
          - {label: "Data wydarzenia", name: "data", widget: "string"}
          - {label: "Miejsce", name: "miejsce", widget: "string"}
